server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 495227986019-n2e3vssosl7p1u9h319rseqtlugbgdjh.apps.googleusercontent.com
            client-secret: jwPnYv9fXExJG-Dzb5TFpk9F
            scope: profile, email
          naver:
            client-id: LoEP_UPQ2q2yL6xe0VJd
            client-secret: xNZ7hh5NgR
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response # 회원정보를 json 타입으로 response라는 키값으로 네이버 결과전달


jpa:
  hibernate:
    ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardimpl
    show-sql: true
